// Code generated by mockery v2.12.1. DO NOT EDIT.

package mocks

import (
	context "context"

	core "github.com/LambdaTest/test-at-scale/pkg/core"
	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// TASConfigManager is an autogenerated mock type for the TASConfigManager type
type TASConfigManager struct {
	mock.Mock
}

// GetVersion provides a mock function with given fields: path
func (_m *TASConfigManager) GetVersion(path string) (int, error) {
	ret := _m.Called(path)

	var r0 int
	if rf, ok := ret.Get(0).(func(string) int); ok {
		r0 = rf(path)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoadAndValidateV1 provides a mock function with given fields: ctx, path, eventType, licenseTier
func (_m *TASConfigManager) LoadAndValidateV1(ctx context.Context, path string, eventType core.EventType, licenseTier core.Tier) (*core.TASConfig, error) {
	ret := _m.Called(ctx, path, eventType, licenseTier)

	var r0 *core.TASConfig
	if rf, ok := ret.Get(0).(func(context.Context, string, core.EventType, core.Tier) *core.TASConfig); ok {
		r0 = rf(ctx, path, eventType, licenseTier)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.TASConfig)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, core.EventType, core.Tier) error); ok {
		r1 = rf(ctx, path, eventType, licenseTier)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoadAndValidateV2 provides a mock function with given fields: ctx, path, eventType, licenseTier
func (_m *TASConfigManager) LoadAndValidateV2(ctx context.Context, path string, eventType core.EventType, licenseTier core.Tier) (*core.TASConfigV2, error) {
	ret := _m.Called(ctx, path, eventType, licenseTier)

	var r0 *core.TASConfigV2
	if rf, ok := ret.Get(0).(func(context.Context, string, core.EventType, core.Tier) *core.TASConfigV2); ok {
		r0 = rf(ctx, path, eventType, licenseTier)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.TASConfigV2)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, core.EventType, core.Tier) error); ok {
		r1 = rf(ctx, path, eventType, licenseTier)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTASConfigManager creates a new instance of TASConfigManager. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewTASConfigManager(t testing.TB) *TASConfigManager {
	mock := &TASConfigManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
