// Code generated by mockery v2.12.1. DO NOT EDIT.

package mocks

import (
	context "context"

	core "github.com/LambdaTest/test-at-scale/pkg/core"
	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// TestExecutionService is an autogenerated mock type for the TestExecutionService type
type TestExecutionService struct {
	mock.Mock
}

// RunV1 provides a mock function with given fields: ctx, tasConfig, payload, coverageDirectory, secretMap
func (_m *TestExecutionService) RunV1(ctx context.Context, tasConfig *core.TASConfig, payload *core.Payload, coverageDirectory string, secretMap map[string]string) (*core.ExecutionResults, error) {
	ret := _m.Called(ctx, tasConfig, payload, coverageDirectory, secretMap)

	var r0 *core.ExecutionResults
	if rf, ok := ret.Get(0).(func(context.Context, *core.TASConfig, *core.Payload, string, map[string]string) *core.ExecutionResults); ok {
		r0 = rf(ctx, tasConfig, payload, coverageDirectory, secretMap)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.ExecutionResults)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *core.TASConfig, *core.Payload, string, map[string]string) error); ok {
		r1 = rf(ctx, tasConfig, payload, coverageDirectory, secretMap)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RunV2 provides a mock function with given fields: ctx, tasConfig, subModule, payload, coverageDir, envMap, target, secretData
func (_m *TestExecutionService) RunV2(ctx context.Context, tasConfig *core.TASConfigV2, subModule *core.SubModule, payload *core.Payload, coverageDir string, envMap map[string]string, target []string, secretData map[string]string) (*core.ExecutionResults, error) {
	ret := _m.Called(ctx, tasConfig, subModule, payload, coverageDir, envMap, target, secretData)

	var r0 *core.ExecutionResults
	if rf, ok := ret.Get(0).(func(context.Context, *core.TASConfigV2, *core.SubModule, *core.Payload, string, map[string]string, []string, map[string]string) *core.ExecutionResults); ok {
		r0 = rf(ctx, tasConfig, subModule, payload, coverageDir, envMap, target, secretData)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.ExecutionResults)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *core.TASConfigV2, *core.SubModule, *core.Payload, string, map[string]string, []string, map[string]string) error); ok {
		r1 = rf(ctx, tasConfig, subModule, payload, coverageDir, envMap, target, secretData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SendResults provides a mock function with given fields: ctx, payload
func (_m *TestExecutionService) SendResults(ctx context.Context, payload *core.ExecutionResults) (*core.TestReportResponsePayload, error) {
	ret := _m.Called(ctx, payload)

	var r0 *core.TestReportResponsePayload
	if rf, ok := ret.Get(0).(func(context.Context, *core.ExecutionResults) *core.TestReportResponsePayload); ok {
		r0 = rf(ctx, payload)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.TestReportResponsePayload)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *core.ExecutionResults) error); ok {
		r1 = rf(ctx, payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTestExecutionService creates a new instance of TestExecutionService. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewTestExecutionService(t testing.TB) *TestExecutionService {
	mock := &TestExecutionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
