name: 🐞 Bug report
description: Create a bug report to help us improve Test-at-scale
title: "[Bug]: "
labels: [bug, needs-triaging]
assignees:
- nevilm-lt
body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this bug report! Please fill the form in English
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  attributes:
    label: What is the current behavior?
    description: Add a brief description of what you are experiencing.
  validations:
    required: true
- type: textarea
  attributes:
    label: What is the expected behavior?
    description: A brief description of what you expect.
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Add steps to reproduce this behavior, include console / network logs & screenshots
    placeholder: |
      1. 
      2. 
      3.
      4.
  validations:
    required: true
- type: dropdown
  id: version
  attributes:
    label: Version
    options:
      - Test-at-scale Cloud
      - Test-at-scale Community Edition
      - Test-at-scale Enterprise Edition
  validations:
    required: true
