// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	core "github.com/LambdaTest/test-at-scale/pkg/core"
	mock "github.com/stretchr/testify/mock"
)

// CoverageService is an autogenerated mock type for the CoverageService type
type CoverageService struct {
	mock.Mock
}

// MergeAndUpload provides a mock function with given fields: ctx, payload
func (_m *CoverageService) MergeAndUpload(ctx context.Context, payload *core.Payload) error {
	ret := _m.Called(ctx, payload)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *core.Payload) error); ok {
		r0 = rf(ctx, payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewCoverageService interface {
	mock.TestingT
	Cleanup(func())
}

// NewCoverageService creates a new instance of CoverageService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCoverageService(t mockConstructorTestingTNewCoverageService) *CoverageService {
	mock := &CoverageService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
