// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// TestStats is an autogenerated mock type for the TestStats type
type TestStats struct {
	mock.Mock
}

// CaptureTestStats provides a mock function with given fields: pid, collectStats
func (_m *TestStats) CaptureTestStats(pid int32, collectStats bool) error {
	ret := _m.Called(pid, collectStats)

	var r0 error
	if rf, ok := ret.Get(0).(func(int32, bool) error); ok {
		r0 = rf(pid, collectStats)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewTestStats interface {
	mock.TestingT
	Cleanup(func())
}

// NewTestStats creates a new instance of TestStats. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTestStats(t mockConstructorTestingTNewTestStats) *TestStats {
	mock := &TestStats{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
