package testutils

// Various constant defined for to obtain dummy data for tests
const (
	ApplicationConfigPath = "/testutils/testdata/sample_config.json"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               // AplicationConfigPath points to dummy config file in json format for NucleusConfig
	TaskPayloadPath       = "/testutils/testdata/taskPayload.json"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 // TaskPayloadPath points to json file containing dummy TaskPayload
	PayloadPath           = "/testutils/testdata/payload.json"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     // PayloadPath points to json file containing dummy PayloadPath
	GitlabCommitDiff      = "/testutils/testdata/gitlabCommitDiff.json"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // GitLabCommitDiff points to json file containing dummy GitLabCommitDiff
	PayloadCheck          = "&{sachin14/nexe https://github.com/sachin14/nexe      main 2850df28b4a043959h65eb6c03772d5c 7572a0f9a08a4130a2265f6eb2470eb5 1cd18453e7f440f1a0kd6418c5a708da github false push  0 [{a0fa2fb0201c62aa541c1a6eba516a8fefd874d8 https://github.com/sachin14/nexe/commit/a0fa2fb0201c62aa541c1a6eba516a8fefd874d8 [] [] [Readme.md] first commit} {60143149e18581ad15b8a76fd2ed96e695d7826e https://github.com/sachin14/nexe/commit/60143149e18581ad15b8a76fd2ed96e695d7826e [] [] [Readme.md] second commit}] .tas.yml   false  false}" // PayloadCheck is used to test FetchPayload
)
