name: Update Docker Hub Description

on:
  push:
    branches:
      - main
    paths:
      - README.md
      - .github/workflows/dockerhub-description.yml

jobs:
  dockerHubDescription:
    name: Update DockerHub Description - Nucleus
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Codebase
      uses: actions/checkout@v3

    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v3
      with:
        # DOCKER_PASSWORD are actual password not token
        # DOCKER_TOKEN is not supported for readme/docs updation in dockerhub
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: lambdatest/nucleus
        short-description: ${{ github.event.repository.description }}

    - name: Docker Hub Description - Synapse
      uses: peter-evans/dockerhub-description@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: lambdatest/synapse
        short-description: ${{ github.event.repository.description }}
